import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { loadConfig } from '../src/config/config.js';
import { createApp } from '../src/app.js';

test('command long polling wakes without heartbeat, retains unacked IDs and isolates devices', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'einform-commands-'));
  const config = await loadConfig();
  config.storage = { dataDir: path.join(dir, 'data'), cacheDir: path.join(dir, 'cache'), logDir: path.join(dir, 'logs') };
  config.render.cacheDir = path.join(dir, 'render'); config.logging.console = false;
  const system = await createApp(config), server = system.app.listen(0, '127.0.0.1');
  await new Promise(r => server.once('listening', r));
  t.after(async () => { system.commands.stopWaiting(); await new Promise(r => server.close(r)); await system.close(); await fs.rm(dir, { recursive: true, force: true }); });
  const url = `http://127.0.0.1:${server.address().port}`;
  const a = '81111111-1111-4111-8111-111111111111', b = '82222222-2222-4222-8222-222222222222';
  await system.registry.heartbeat({ internalUuid: a, deviceId: 'A', siteId: 'A' }, '127.0.0.1');
  await system.registry.heartbeat({ internalUuid: b, deviceId: 'B', siteId: 'B' }, '127.0.0.1');
  const lastHeartbeat = system.registry.byUuid(a).lastSeen;
  const waiting = fetch(`${url}/api/device/A/commands?internalUuid=${a}&wait=25&after=0`);
  // Wait until the HTTP request is actually parked, then enqueue a command.
  for (let i = 0; i < 100 && !system.commands.waiters.has(a); i++) await new Promise(r => setTimeout(r, 5));
  assert.ok(system.commands.waiters.has(a));
  await system.registry.edit(a, { deviceId: 'RENAMED' });
  const start = Date.now(), command = await system.commands.enqueue(a, 'restart_app');
  const result = await (await waiting).json();
  assert.ok(Date.now() - start < 1000, 'delivery must wake immediately instead of waiting for heartbeat');
  assert.equal(result.deviceId, 'RENAMED'); assert.equal(result.commands[0].id, command.id);
  assert.equal(system.registry.byUuid(a).lastSeen, lastHeartbeat);
  const duplicate = await (await fetch(`${url}/api/device/RENAMED/commands?internalUuid=${a}&wait=0&after=${result.cursor}`)).json();
  assert.equal(duplicate.commands[0].id, command.id, 'cursor must not hide commands lost during a client crash');
  assert.deepEqual((await (await fetch(`${url}/api/device/B/commands?internalUuid=${b}&wait=0`)).json()).commands, []);
  const ack = await fetch(`${url}/api/device/command/${command.id}/ack`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ internalUuid: a, status: 'completed' }) });
  assert.equal(ack.status, 200);
  assert.deepEqual((await (await fetch(`${url}/api/device/RENAMED/commands?internalUuid=${a}&wait=0`)).json()).commands, []);
  assert.equal((await fetch(`${url}/api/device/RENAMED/commands?internalUuid=${a}&wait=26`)).status, 400);
  const abort = new AbortController();
  const interrupted = fetch(`${url}/api/device/RENAMED/commands?internalUuid=${a}&wait=25`, { signal: abort.signal });
  for (let i = 0; i < 100 && !system.commands.waiters.has(a); i++) await new Promise(r => setTimeout(r, 5));
  abort.abort(); await assert.rejects(interrupted);
  for (let i = 0; i < 100 && system.commands.waiters.has(a); i++) await new Promise(r => setTimeout(r, 5));
  assert.equal(system.commands.waiters.size, 0, 'disconnected clients must release timers and waiters');
  const login = await fetch(`${url}/api/admin/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username: config.admin.username, password: config.admin.password }) });
  const cookie = login.headers.get('set-cookie').split(';')[0], csrf = (await login.json()).data.csrfToken;
  const maintenance = await fetch(`${url}/api/admin/device/${a}/show-maintenance`, { method: 'POST', headers: { cookie, 'x-csrf-token': csrf, 'content-type': 'application/json' }, body: '{}' });
  assert.equal(maintenance.status, 200);
  const mode = await (await fetch(`${url}/api/device/RENAMED/commands?internalUuid=${a}&wait=0`)).json();
  assert.equal(mode.displayMode, 'maintenance'); assert.equal(mode.commands[0].type, 'show_maintenance');
});

test('scheduled refresh commands coalesce offline updates without changing delivered image IDs', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'einform-auto-commands-'));
  const config = await loadConfig(); config.storage = { dataDir: path.join(dir, 'data'), cacheDir: path.join(dir, 'cache'), logDir: path.join(dir, 'logs') };
  config.render.cacheDir = path.join(dir, 'render'); config.logging.console = false;
  const system = await createApp(config);
  t.after(async () => { await system.close(); await fs.rm(dir, { recursive: true, force: true }); });
  const id = '83333333-3333-4333-8333-333333333333'; await system.registry.heartbeat({ internalUuid: id, deviceId: 'C', siteId: 'C' }, '127.0.0.1');
  const deadline = new Date(Date.now() + 86400000).toISOString();
  const first = await system.commands.enqueueAutomaticRefresh(id, { imageId: 'first', revision: 'first' }, deadline);
  const replacement = await system.commands.enqueueAutomaticRefresh(id, { imageId: 'second', revision: 'second' }, deadline);
  assert.equal(first.id, replacement.id); assert.equal(replacement.payload.imageId, 'second');
  await system.commands.deliver(id);
  const next = await system.commands.enqueueAutomaticRefresh(id, { imageId: 'third', revision: 'third' }, deadline);
  assert.notEqual(next.id, first.id);
  assert.equal(system.commands.list(id).find(c => c.id === first.id).payload.imageId, 'second');
  for (let i = 0; i < 20; i++) await system.commands.enqueueAutomaticRefresh(id, { imageId: `later-${i}`, revision: `later-${i}` }, deadline);
  assert.equal(system.commands.list(id).filter(c => c.status === 'pending').length, 2);
  await system.commands.ack(first.id, { internalUuid: id, status: 'completed' });
  assert.equal(system.commands.list(id).find(c => c.id === next.id).status, 'pending');
  // Hold the queue as though a disk write were busy; a manual mode change must win.
  let release; const gate = new Promise(resolve => { release = resolve; });
  const blocked = system.commands.store.update(async () => { await gate; });
  const scheduled = system.commands.enqueueAutomaticRefresh(id, { imageId: 'old-normal', revision: 'old' }, deadline, { profile: system.registry.byUuid(id).profile, mode: 'normal' });
  await system.registry.setMode(id, 'maintenance');
  const cancellation = system.commands.cancelAutomaticRefresh(id);
  release(); await blocked; assert.equal(await scheduled, null); await cancellation;
  const manual = await system.commands.enqueue(id, 'show_maintenance');
  const pending = await system.commands.deliver(id);
  assert.deepEqual(pending.map(c => c.id), [manual.id], 'queued automatic PNG must not override a newer manual mode');
});
