import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import YAML from 'yaml';
import sharp from 'sharp';
import { loadConfig } from '../src/config/config.js';
import { createApp } from '../src/app.js';
import { DeviceRegistry, DEMO_UUID } from '../src/device/registry.js';
import { JsonStore } from '../src/storage/json-store.js';

const deviceUuid = '22222222-2222-4222-8222-222222222222';
test('file profiles, editable layout, immutable image selection, expiry, and restart persistence', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'easydesk-images-'));
  const config = await loadConfig();
  config.storage.dataDir = path.join(directory, 'data'); config.storage.cacheDir = path.join(directory, 'cache'); config.storage.logDir = path.join(directory, 'logs');
  config.render.cacheDir = path.join(directory, 'render'); config.render.profileDir = path.join(directory, 'profiles'); config.logging.console = false;
  const configFile = path.join(directory, 'config.yaml'); await fs.writeFile(configFile, YAML.stringify(config));
  const previousEnv = process.env.EASYDESK_CONFIG; process.env.EASYDESK_CONFIG = configFile;
  const system = await createApp(config), server = system.app.listen(0, '127.0.0.1'); await new Promise(r => server.once('listening', r));
  t.after(async () => { if (previousEnv) process.env.EASYDESK_CONFIG = previousEnv; else delete process.env.EASYDESK_CONFIG; await new Promise(r => server.close(r)); await system.close(); await fs.rm(directory, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}`; let cookie = '', csrf = '';
  const call = (route, method = 'GET', body) => fetch(base + '/api/admin/' + route, { method, headers: { 'content-type': 'application/json', cookie, 'x-csrf-token': csrf }, body: body === undefined ? undefined : JSON.stringify(body) });
  assert.equal((await call('images')).status, 401);
  const login = await call('login', 'POST', { username: config.admin.username, password: config.admin.password }); cookie = login.headers.get('set-cookie').split(';')[0]; csrf = (await login.json()).data.csrfToken;
  assert.equal(system.registry.list().length, 0);
  const direct = await call('render/profiles', 'POST', { id: 'direct-pixels', label: '直接指定像素', width: 640, height: 384, template: 'standard' });
  assert.equal(direct.status, 201); const directProfile = (await direct.json()).data.profile;
  assert.deepEqual(directProfile.canvas, { width: 640, height: 384 });
  assert.ok(directProfile.layout.some(b => b.type === 'lunar'));
  assert.equal((await call('render/profiles', 'POST', { id: 'direct-pixels', label: '重复', width: 640, height: 384, template: 'blank' })).status, 400);
  assert.equal((await call('render/profiles', 'POST', { id: 'blank-pixels', label: '空白', width: 480, height: 800, template: 'blank' })).status, 201);
  assert.deepEqual(config.render.profiles['blank-pixels'].canvas, { width: 480, height: 800 });
  assert.equal((await call('render/profiles', 'POST', { id: 'bad-pixels', label: '错误', width: 10, height: 800, template: 'blank' })).status, 400);
  assert.equal((await call('weather/lookup', 'POST', { query: '浦东新区' })).status, 400); // no production credentials
  const custom = { label: '横屏桌面', width: 800, height: 480, canvas: { width: 800, height: 480 }, layout: [{ id: 'greeting', type: 'text', x: 25, y: 25, width: 750, height: 420, fontSize: 40, enabled: true, text: '你好 {{date}}\n可编辑中文排版', bold: true }] };
  assert.equal((await call('render/profiles/my-desk', 'PUT', { profile: custom })).status, 200);
  assert.equal(YAML.parse(await fs.readFile(path.join(config.render.profileDir, 'my-desk.yaml'), 'utf8')).width, 800);
  assert.equal((await call('render/profiles/%2E%2E%2Foutside', 'PUT', { profile: custom })).status, 400);
  assert.equal((await call('render/profiles/my-desk', 'PUT', { yaml: 'layout: [' })).status, 400);
  assert.equal((await call('render/profiles/my-desk', 'PUT', { profile: { ...custom, layout: [{ ...custom.layout[0], x: 790 }] } })).status, 400);
  assert.equal((await call('render/profiles/my-desk')).status, 200);
  const generate = async () => { const r = await call('images/generate', 'POST', { profile: 'my-desk', auto: true }); assert.equal(r.status, 201); return (await r.json()).data; };
  const first = await generate(); const firstPng = Buffer.from(await (await fetch(base + first.image)).arrayBuffer());
  const size = await sharp(firstPng).metadata(); assert.equal(size.width, 800); assert.equal(size.height, 480); assert.equal(size.channels, 1); assert.equal(size.bitsPerSample, 8);
  assert.equal(Date.parse(first.expiresAt) - Date.parse(first.generatedAt), 3 * 86400000);
  assert.equal(system.registry.list().length, 0);
  custom.layout[0].text = '已修改内容'; custom.layout[0].fontSize = 55;
  await call('render/profiles/my-desk', 'PUT', { profile: custom });
  const second = await generate(); assert.notEqual(first.imageId, second.imageId); assert.notEqual(first.pngHash, second.pngHash);
  assert.equal((await call('images')).status, 200); assert.equal(system.images.list().length, 2);
  assert.equal((await fetch(base + first.image, { headers: { 'if-none-match': first.etag } })).status, 304);
  await system.registry.heartbeat({ internalUuid: deviceUuid, deviceId: 'REAL-DESK', profile: 'my-desk' }, '127.0.0.1');
  const selected = await call(`device/${deviceUuid}/refresh`, 'POST', { imageId: first.imageId }); assert.equal(selected.status, 200);
  const delivered = await system.commands.deliver(deviceUuid); assert.equal(delivered[0].payload.image, first.image); assert.equal(delivered[0].payload.imageId, first.imageId);
  assert.deepEqual((await system.display.get('REAL-DESK')).png, firstPng);
  const restored = await createApp(config); assert.equal(restored.registry.byUuid(deviceUuid).selectedImageId, first.imageId); assert.deepEqual((await restored.display.get('REAL-DESK')).png, firstPng); await restored.close();
  assert.equal((await fetch(base + '/api/admin/images/' + first.imageId, { method: 'DELETE', headers: { cookie } })).status, 403);
  assert.equal((await call('images/' + first.imageId, 'DELETE')).status, 200);
  assert.equal((await fetch(base + first.image)).status, 404);
  assert.ok(!system.images.list().some(i => i.imageId === first.imageId)); assert.ok(system.images.list(true).some(i => i.imageId === first.imageId));
  assert.equal(system.registry.byUuid(deviceUuid).selectedImageId, null);
  assert.ok((await system.commands.deliver(deviceUuid)).every(c => c.payload?.imageId !== first.imageId));
  assert.notEqual((await system.display.get('REAL-DESK')).imageId, first.imageId);
  const trashedRestart = await createApp(config); assert.ok(trashedRestart.images.list(true).some(i => i.imageId === first.imageId)); await assert.rejects(trashedRestart.images.read(first.imageId), { status: 404 }); await trashedRestart.close();
  assert.equal((await call('images/' + first.imageId + '/restore', 'POST', {})).status, 200);
  assert.deepEqual(Buffer.from(await (await fetch(base + first.image)).arrayBuffer()), firstPng);
  assert.equal((await call(`device/${deviceUuid}/refresh`, 'POST', { imageId: first.imageId })).status, 200);
  const settings = await call('render', 'PUT', { retentionDays: 3, intervalSeconds: 600, enabled: true, adaptive: true, defaultProfile: 'my-desk' }); assert.equal(settings.status, 200);
  assert.equal(YAML.parse(await fs.readFile(configFile, 'utf8')).render.defaultProfile, 'my-desk');
  const keep = path.join(config.render.cacheDir, 'keep-me.png'); await fs.writeFile(keep, 'unrelated user file');
  await system.images.store.update(entries => { entries[first.imageId].expiresAt = new Date(Date.now() - 1).toISOString(); });
  assert.equal((await fetch(base + first.image)).status, 410);
  await system.images.cleanup(); await assert.rejects(fs.access(path.join(config.render.cacheDir, first.file)), { code: 'ENOENT' });
  assert.equal(await fs.readFile(keep, 'utf8'), 'unrelated user file'); assert.equal((await fetch(base + second.image)).status, 200);
  const automatic = await system.display.get('REAL-DESK'); assert.notEqual(automatic.imageId, first.imageId); assert.equal(system.registry.byUuid(deviceUuid).selectedImageId, null);
  assert.equal((await call('render/profiles/reload', 'POST', {})).status, 200);
});

test('only the unused historical preview seed is removed, real registrations survive', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'easydesk-seed-')); t.after(() => fs.rm(directory, { recursive: true, force: true }));
  const config = await loadConfig(); config.storage.dataDir = directory; const log = { info() {}, warn() {} };
  const seed = { internalUuid: DEMO_UUID, deviceId: 'Z9-001', siteId: 'DESK-SH-001', lastSeen: null };
  const other = { internalUuid: deviceUuid, deviceId: 'REAL', siteId: 'REAL', lastSeen: '2026-10-02T00:00:00Z' };
  await new JsonStore(path.join(directory, 'devices.json'), { [DEMO_UUID]: seed, [deviceUuid]: other }).init();
  const registry = await new DeviceRegistry(config, log).init(); assert.equal(registry.list().length, 1); assert.equal(registry.byUuid(deviceUuid).deviceId, 'REAL');
  await registry.heartbeat({ internalUuid: DEMO_UUID, deviceId: 'Z9-001', siteId: 'DESK-SH-001' }, '127.0.0.1');
  const restarted = await new DeviceRegistry(config, log).init(); assert.equal(restarted.list().length, 2);
});

test('adaptive scheduling respects weather expiry and content boundaries without early rendering', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'easydesk-schedule-')); t.after(() => fs.rm(directory, { recursive: true, force: true }));
  const config = await loadConfig(); config.storage.dataDir = path.join(directory, 'data'); config.storage.cacheDir = path.join(directory, 'cache'); config.storage.logDir = path.join(directory, 'logs'); config.render.cacheDir = path.join(directory, 'render'); config.logging.console = false;
  const system = await createApp(config); t.after(() => system.close());
  const now = Date.parse('2026-10-02T10:15:00+08:00'), d = { internalUuid: deviceUuid };
  config.weather.ttlSeconds.alerts = 120;
  assert.equal(Date.parse(system.display.nextAt(d, { status: { alerts: { updatedAt: new Date(now).toISOString() } } }, now)), now + 120000);
  system.display.content = { list: () => [{ internalUuid: deviceUuid, startsAt: new Date(now + 45000).toISOString() }], active: () => [] };
  assert.equal(Date.parse(system.display.nextAt(d, {}, now)), now + 45000);
  config.render.generation.adaptive = false;
  assert.equal(Date.parse(system.display.nextAt(d, {}, now)), now + config.render.generation.intervalSeconds * 1000);
  const image = await system.display.preview({ profile: config.render.defaultProfile, auto: true });
  let renders = 0; const original = system.renderer.render.bind(system.renderer); system.renderer.render = model => { renders++; return original(model); };
  await system.display.tick(); assert.equal(renders, 0);
  system.display.invalidate(); await system.display.tick(); assert.equal(renders, 0); // unchanged inputs reuse the PNG
  assert.equal(system.images.list()[0].imageId, image.imageId);
  config.render.profiles[config.render.defaultProfile].layout[0].text = '自动更新后的标题';
  system.display.invalidate(); await system.display.tick(); assert.equal(renders, 1);
});
