import fs from 'node:fs/promises';
import path from 'node:path';
import { loadConfig, root } from '../src/config/config.js';
import { createApp } from '../src/app.js';
import { getAlmanac } from '../src/almanac/lunar.js';
import { dateParts } from '../src/time.js';
import { MockWeatherProvider } from '../src/weather/mock.js';

const config = await loadConfig();
const system = await createApp(config);
const { renderer } = system;
const now = new Date('2026-10-02T10:15:00+08:00');
const mock = new MockWeatherProvider(config.server.timezone);
const example = Object.fromEntries(await Promise.all(['now', 'hourly', 'daily', 'air', 'alerts'].map(async kind => [kind, await mock.fetch(kind, config.location, now)])));
const model = { device: { deviceId: 'PREVIEW', siteId: 'PREVIEW', location: config.location, profile: config.render.defaultProfile, preview: true, online: false }, now: now.toISOString(), timezone: config.server.timezone, updatedTime: dateParts(now, config.server.timezone).time, almanac: getAlmanac(now, config.server.timezone), weather: { ...example, source: 'mock' } };
const output = path.join(root, 'artifacts');
await fs.mkdir(output, { recursive: true });
await fs.writeFile(path.join(output, 'z9-normal.png'), await renderer.render(model));
model.weather.alerts = [{ title: '暴雨橙色预警', sender: '上海中心气象台', publishedAt: now.toISOString() }];
await fs.writeFile(path.join(output, 'z9-alert.png'), await renderer.render(model));
model.mode = 'maintenance';
model.maintenanceDevice = { ...model.device, battery: 83, charging: true, ip: '192.168.51.37', mac: '4C:72:B9:12:34:56', rssi: -47, androidVersion: '4.4.2', appVersion: '0.1.0', uptime: 184022, lastSeen: now.toISOString(), contentRevision: 'example-20261002' };
model.serverUrl = 'http://192.168.51.10:8066';
await fs.writeFile(path.join(output, 'z9-maintenance.png'), await renderer.render(model));
console.log(`Previews: ${output}`);
await system.close();
